### ISSUE TITLE
Determine possible data model

### ISSUE THREAD

**Issue by jbytecoder** [Henrar/LambdaStackProject#16]
Based on the Twitter API, and capapilities of SPARK we need to decide what will be our data model. What kind of entities can we store.   Resolution of this issue should contain some sort of non-strict ERD database model

**Comment by henrar** [comment]
I don't think we need to store UserNames from Twitter (unless we want to see how many negative/positive tweets given user has). I believe we need to store hashtags in DB (add them as they arrive from twitter), maybe date of birth of users, something like that? I believe we should also add dates to monitor mood changes on Twitter

Storing entire tweets would kill the database with their size.

**Comment by jbytecoder** [comment]
Absolutley storing tweets is out of question. Tweets apear only in sprak for processiong.

 I intented something like this. We have kewords and their categrories and those are completely arbitral - defined by user.  We can monitor moods by creating category positive and negative and assining some keywords to them.  But we can also define  category cursewords and monitor who uses them the most.  And now how to process data.  I'm not clear about hash tags but I belive we should process latest tweets as they appear and look for choosen tags - and while doing so count keywords. I also thougt we can process tweets of particular user, looking for keywords that's why i need user twitter ids, and they names to present something in frontend.  

I think i added dates where needed. HashTagKeywordUsage has no date because it is tied to HashTagCategoryUsage which has date

**Comment by jbytecoder** [comment]
There is a ERD diagram of database in wiki. Case closed
