### ISSUE TITLE
Find project's coordinator

### ISSUE THREAD

**Issue by rapsad** [Henrar/LambdaStackProject#8]
Arkadiusz Janik
 Marcin Jarząb
 Marek Konieczny
 Filip Malawski
 Marek Psiuk
 Kornel Skałkowski
 Daniel Żmuda

Which one?

**Comment by rapsad** [comment]
What do you think? @Henrar @jbytecoder

**Comment by henrar** [comment]
I think Kornel Skałkowski and Arkadiusz Janik should suffice
